
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/wouldyou/website
            git pull origin main
            git status
            pnpm install
            pnpm lint
            pnpm build
            pm2 restart Would-You-Website