name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: "18.x" # Use the desired Node.js version

      - name: Install pnpm and pm2
        run: |
          npm install -g pnpm
          npm install -g pm2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/wouldyou/website
            git pull origin main
            git status

      - name: Install dependencies
        run: |
          cd /home/wouldyou/website
          pnpm install

      - name: Run lint
        run: |
          cd /home/wouldyou/website
          pnpm lint

      - name: Build website
        run: |
          cd /home/wouldyou/website
          pnpm build

      - name: Restart process with PM2
        run: |
          # Navigate to your application directory
          cd /home/wouldyou/website

          pm2 restart Would-You-Website
